#!/usr/bin/env python3
"""Render the canonical repo-local OpenArm URDF from the official xacro source."""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import tempfile
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REPO_URL = "https://github.com/enactic/openarm_description.git"
DEFAULT_REPO_REF = "79cd8b7cb5a22a0ce6de90e860d120cbc33085ac"
DEFAULT_OUTPUT = PROJECT_ROOT / "assets" / "robots" / "openarm" / "openarm_v10_hand.urdf"
ROOT_XACRO = Path("urdf") / "robot" / "v10.urdf.xacro"

EXPECTED_JOINTS = (
    "openarm_joint1",
    "openarm_joint2",
    "openarm_joint3",
    "openarm_joint4",
    "openarm_joint5",
    "openarm_joint6",
    "openarm_joint7",
    "openarm_finger_joint1",
    "openarm_finger_joint2",
)
EXPECTED_LINKS = ("openarm_hand", "openarm_hand_tcp")


def _require_tool(name: str) -> None:
    if shutil.which(name):
        return
    raise RuntimeError(f"Required tool not found in PATH: {name}")


def _run(cmd: list[str], cwd: Path | None = None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        cmd,
        cwd=str(cwd) if cwd else None,
        check=True,
        capture_output=True,
        text=True,
    )


def _checkout_repo(repo_url: str, ref: str, checkout_dir: Path) -> Path:
    _run(["git", "init", "-q", str(checkout_dir)])
    _run(["git", "-C", str(checkout_dir), "remote", "add", "origin", repo_url])
    _run(["git", "-C", str(checkout_dir), "fetch", "--depth", "1", "origin", ref])
    _run(["git", "-C", str(checkout_dir), "checkout", "--detach", "-q", "FETCH_HEAD"])
    return checkout_dir


def _rewrite_package_finds(repo_root: Path) -> None:
    for path in repo_root.rglob("*"):
        if not path.is_file() or path.suffix not in {".xacro", ".yaml", ".xml", ".urdf"}:
            continue
        text = path.read_text(encoding="utf-8")
        if "$(find openarm_description)" not in text:
            continue
        path.write_text(
            text.replace("$(find openarm_description)", str(repo_root.resolve())),
            encoding="utf-8",
        )


def _validate_rendered_urdf(urdf_text: str) -> None:
    missing = []
    for name in EXPECTED_JOINTS:
        if not re.search(rf'<joint[^>]*name="{re.escape(name)}"', urdf_text):
            missing.append(name)
    for name in EXPECTED_LINKS:
        if not re.search(rf'<link[^>]*name="{re.escape(name)}"', urdf_text):
            missing.append(name)
    if missing:
        raise RuntimeError(f"Rendered OpenArm URDF is missing expected elements: {missing}")


def _normalize_header(urdf_text: str, repo_url: str, repo_ref: str) -> str:
    autogenerated = re.compile(
        r'<!-- =+ -->\s*'
        r'<!-- \|\s+This document was autogenerated by xacro from .*? \| -->\s*'
        r'<!-- \|\s+EDITING THIS FILE BY HAND IS NOT RECOMMENDED\s+\| -->\s*'
        r'<!-- =+ -->\s*',
        re.DOTALL,
    )
    replacement = (
        f"<!-- Generated by scripts/build_openarm_local_urdf.py from {repo_url}@{repo_ref} -->\n"
    )
    return autogenerated.sub(replacement, urdf_text, count=1)


def build_openarm_urdf(output_path: Path, repo_url: str, repo_ref: str) -> Path:
    _require_tool("git")
    _require_tool("xacro")

    output_path.parent.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory(prefix="openarm_description_") as tmpdir:
        repo_root = _checkout_repo(repo_url, repo_ref, Path(tmpdir) / "openarm_description")
        _rewrite_package_finds(repo_root)
        rendered = _run(
            [
                "xacro",
                str(repo_root / ROOT_XACRO),
                "arm_type:=v10",
                "body_type:=v10",
                "ee_type:=openarm_hand",
                "hand:=true",
                "ros2_control:=false",
                "bimanual:=false",
            ],
            cwd=repo_root,
        ).stdout

    rendered = _normalize_header(rendered, repo_url=repo_url, repo_ref=repo_ref)
    _validate_rendered_urdf(rendered)
    output_path.write_text(rendered, encoding="utf-8")
    return output_path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Rendered URDF output path")
    parser.add_argument("--repo-url", default=DEFAULT_REPO_URL, help="Official OpenArm description repository")
    parser.add_argument("--repo-ref", default=DEFAULT_REPO_REF, help="Git ref or commit to render from")
    args = parser.parse_args()

    output_path = args.output.expanduser()
    if not output_path.is_absolute():
        output_path = (PROJECT_ROOT / output_path).resolve()
    built = build_openarm_urdf(output_path, repo_url=args.repo_url, repo_ref=args.repo_ref)
    print(f"Built local OpenArm URDF: {built}")
    print(f"  source: {args.repo_url}@{args.repo_ref}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
