#!/usr/bin/env python3
"""Evaluate captured debug screenshots using Claude VLM.

Usage:
    python scripts/evaluate_scene.py outputs/isaaclab/franka_stack_20260330_143022/
    python scripts/evaluate_scene.py outputs/isaaclab/franka_stack_20260330_143022/ --task-yaml tasks/franka/stack/franka_stack.yaml
"""

import argparse
import base64
import json
import os
import sys
from datetime import datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from dotenv import load_dotenv
load_dotenv(PROJECT_ROOT / ".env")


def encode_image(image_path: Path) -> str:
    """Read an image file and return base64-encoded string."""
    with open(image_path, "rb") as f:
        return base64.b64encode(f.read()).decode("utf-8")


def build_evaluation_prompt(task_yaml_content: str | None) -> str:
    """Build the VLM evaluation prompt."""
    base = """You are evaluating a robotics simulation environment generated by an AI system.
You are shown screenshots of an IsaacLab environment from multiple camera angles.

Evaluate the scene on these criteria (score each 0-25, total 0-100):

1. **Scene Completeness** (0-25): Are all expected objects present? (robot, table, task objects)
2. **Object Placement** (0-25): Are objects positioned correctly on the table? Reasonable spatial arrangement?
3. **Robot Configuration** (0-25): Is the robot properly spawned? Correct initial pose? End-effector visible?
4. **Visual Quality** (0-25): Is the scene well-lit? No visual artifacts? Objects have reasonable colors/textures?

"""
    if task_yaml_content:
        base += f"""The task YAML specification is:
```yaml
{task_yaml_content}
```

Compare the scene against this specification. Check if the objects described in the YAML
are actually present and correctly configured in the scene.

"""

    base += """Respond in this exact JSON format:
```json
{
    "scene_completeness": {"score": <0-25>, "details": "<what's present/missing>"},
    "object_placement": {"score": <0-25>, "details": "<placement assessment>"},
    "robot_configuration": {"score": <0-25>, "details": "<robot state assessment>"},
    "visual_quality": {"score": <0-25>, "details": "<visual quality notes>"},
    "total_score": <0-100>,
    "summary": "<1-2 sentence overall assessment>",
    "issues": ["<issue 1>", "<issue 2>"]
}
```"""
    return base


def evaluate_with_claude(image_paths: list[Path], task_yaml_content: str | None = None) -> dict:
    """Call Claude API to evaluate the scene screenshots.

    Args:
        image_paths: List of screenshot paths (front.png, top.png, wrist.png).
        task_yaml_content: Optional task YAML content for comparison.

    Returns:
        Parsed evaluation result dict.
    """
    try:
        import anthropic
    except ImportError:
        print("ERROR: anthropic package not installed. Run: pip install anthropic")
        sys.exit(1)

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("ERROR: ANTHROPIC_API_KEY not set")
        sys.exit(1)

    client = anthropic.Anthropic(api_key=api_key)

    # Build message content with images
    content = []
    for img_path in image_paths:
        if not img_path.exists():
            continue
        angle = img_path.stem  # "front", "top", "wrist"
        content.append({"type": "text", "text": f"[{angle.upper()} view]"})
        content.append({
            "type": "image",
            "source": {
                "type": "base64",
                "media_type": "image/png",
                "data": encode_image(img_path),
            },
        })

    if not any(c.get("type") == "image" for c in content):
        return {"error": "No valid images found", "total_score": 0}

    content.append({
        "type": "text",
        "text": build_evaluation_prompt(task_yaml_content),
    })

    model = os.environ.get("CLAUDE_MODEL", "claude-sonnet-4-20250514")
    response = client.messages.create(
        model=model,
        max_tokens=2000,
        messages=[{"role": "user", "content": content}],
    )

    # Parse response
    response_text = response.content[0].text
    # Extract JSON from markdown code block if present
    if "```json" in response_text:
        json_str = response_text.split("```json")[1].split("```")[0].strip()
    elif "```" in response_text:
        json_str = response_text.split("```")[1].split("```")[0].strip()
    else:
        json_str = response_text.strip()

    try:
        return json.loads(json_str)
    except json.JSONDecodeError:
        return {
            "error": "Failed to parse VLM response",
            "raw_response": response_text,
            "total_score": 0,
        }


def main():
    parser = argparse.ArgumentParser(description="Evaluate IsaacLab scene screenshots with Claude VLM")
    parser.add_argument("output_dir", help="Path to output directory containing debug/ folder")
    parser.add_argument("--task-yaml", type=str, help="Path to task YAML for comparison")
    parser.add_argument("--save", action="store_true", default=True, help="Save evaluation to debug/vlm_eval.json")
    args = parser.parse_args()

    output_dir = Path(args.output_dir).resolve()
    debug_dir = output_dir / "debug"

    if not debug_dir.exists():
        print(f"ERROR: debug/ folder not found in {output_dir}")
        sys.exit(1)

    # Collect images
    image_paths = []
    for angle in ["front", "top", "wrist"]:
        img = debug_dir / f"{angle}.png"
        if img.exists():
            image_paths.append(img)
            print(f"  Found: {img.name}")
        else:
            print(f"  Missing: {angle}.png")

    if not image_paths:
        print("ERROR: No screenshots found in debug/")
        sys.exit(1)

    # Load task YAML if provided
    task_yaml_content = None
    # Try to find task.yaml in output_dir first
    task_yaml_path = output_dir / "task.yaml"
    if args.task_yaml:
        task_yaml_path = Path(args.task_yaml)
    if task_yaml_path.exists():
        task_yaml_content = task_yaml_path.read_text()
        print(f"  Using task YAML: {task_yaml_path}")

    # Evaluate
    print("\nEvaluating with Claude VLM...")
    result = evaluate_with_claude(image_paths, task_yaml_content)

    # Display
    print(f"\n{'='*60}")
    print(f"  Total Score: {result.get('total_score', 'N/A')}/100")
    print(f"{'='*60}")
    for key in ["scene_completeness", "object_placement", "robot_configuration", "visual_quality"]:
        if key in result:
            item = result[key]
            print(f"  {key}: {item.get('score', '?')}/25 - {item.get('details', '')}")
    if "summary" in result:
        print(f"\n  Summary: {result['summary']}")
    if result.get("issues"):
        print(f"\n  Issues:")
        for issue in result["issues"]:
            print(f"    - {issue}")

    # Save
    if args.save:
        eval_path = debug_dir / "vlm_eval.json"
        result["evaluated_at"] = datetime.now().isoformat()
        result["images"] = [str(p) for p in image_paths]
        with open(eval_path, "w") as f:
            json.dump(result, f, indent=2, ensure_ascii=False)
        print(f"\n  Saved to: {eval_path}")

    return result


if __name__ == "__main__":
    main()
